name: Deploy Flask API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Hugging Face CLI
      run: |
        pip install huggingface-hub

    - name: Log in to Hugging Face CLI
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        huggingface-cli login --token $HF_TOKEN

    - name: Deploy to Hugging Face
      run: |
        # Replace `my-space` with your Hugging Face Space name
        huggingface-cli repo create my-space --type=space
        git init
        git add .
        git commit -m "Initial commit"
        git branch -M main
        git remote add origin https://huggingface.co/spaces/username/my-space
        git push -u origin main
