name: Deploy Flask API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Hugging Face CLI
      run: |
        pip install huggingface_hub

    - name: Create Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python -c "import os from huggingface_hub import HfApi api = HfApi() api.create_repo(name='my-space', repo_type='space', token=os.getenv('HF_TOKEN'))"

    - name: Deploy to Hugging Face
      run: |
        git init
        git add .
        git commit -m "Initial commit"
        git branch -M main
        git remote add origin https://huggingface.co/spaces/username/my-space
        git push -u origin main
